/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2025-01-20T08:43:15.771Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks
    | ContactForm
    | Product
    | Size;

  export type AnySpaceCTDHydrated =
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated
    | ContactFormHydrated
    | ProductHydrated
    | SizeHydrated;

  export type AnySpaceCTDHydratedTwice =
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice
    | ContactFormHydratedTwice
    | ProductHydratedTwice
    | SizeHydratedTwice;

  // #region contact_form

  export interface ContactFormBase extends BaseObject<"contact_form"> {
    name: string;
    email: string;
    question: string;
  }

  export interface ContactForm extends ContactFormBase {}

  export interface ContactFormHydrated extends ContactFormBase {}

  export interface ContactFormHydratedTwice extends ContactFormBase {}

  export namespace ContactForm {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "email" | "question"
    >;
  }

  // #endregion

  // #region product

  export interface ProductBase extends BaseObject<"product"> {
    name: string;

    /**
     * Slug can only have alphanumerical characters, - and _
     */
    slug: string;
    price: number;
    description?: string;
    productImage?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>;
    productGallery?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>;
    sizes?:
      | Array<DataLink>
      | Array<Size>
      | Array<SizeHydrated>
      | Array<SizeHydratedTwice>;
    __translations?: Array<Product._translationsBase>;
  }

  export interface Product extends ProductBase {
    productImage?: Array<DataLink>;
    productGallery?: Array<DataLink>;
    sizes?: Array<DataLink>;
    __translations?: Array<Product._translations>;
  }

  export interface ProductHydrated extends ProductBase {
    productImage?: Array<InternalMedia>;
    productGallery?: Array<InternalMedia>;
    sizes?: Array<Size>;
    __translations?: Array<Product._translationsHydrated>;
  }

  export interface ProductHydratedTwice extends ProductBase {
    productImage?: Array<InternalMediaHydrated>;
    productGallery?: Array<InternalMediaHydrated>;
    sizes?: Array<SizeHydrated>;
    __translations?: Array<Product._translationsHydratedTwice>;
  }

  export namespace Product {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "slug"
      | "price"
      | "description"
      | "productImage"
      | "productImage[*].type"
      | "productImage[*].dataUrl"
      | "productGallery"
      | "productGallery[*].type"
      | "productGallery[*].dataUrl"
      | "sizes"
      | "sizes[*].type"
      | "sizes[*].dataUrl"
      | "__translations"
      | "__translations[*].name"
      | "__translations[*].slug"
      | "__translations[*].price"
      | "__translations[*].description"
      | "__translations[*].productImage"
      | "__translations[*].productImage[*].type"
      | "__translations[*].productImage[*].dataUrl"
      | "__translations[*].productGallery"
      | "__translations[*].productGallery[*].type"
      | "__translations[*].productGallery[*].dataUrl"
      | "__translations[*].sizes"
      | "__translations[*].sizes[*].type"
      | "__translations[*].sizes[*].dataUrl"
      | "__translations[*].__language"
    >;

    // #region Product.__translations

    export interface _translationsBase {
      name: string;

      /**
       * Slug can only have alphanumerical characters, - and _
       */
      slug: string;
      price: number;
      description?: string;
      productImage?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>;
      productGallery?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>;
      sizes?:
        | Array<DataLink>
        | Array<Size>
        | Array<SizeHydrated>
        | Array<SizeHydratedTwice>;
      __language: string;
    }

    export interface _translations extends _translationsBase {
      productImage?: Array<DataLink>;
      productGallery?: Array<DataLink>;
      sizes?: Array<DataLink>;
    }

    export interface _translationsHydrated extends _translationsBase {
      productImage?: Array<InternalMedia>;
      productGallery?: Array<InternalMedia>;
      sizes?: Array<Size>;
    }

    export interface _translationsHydratedTwice extends _translationsBase {
      productImage?: Array<InternalMediaHydrated>;
      productGallery?: Array<InternalMediaHydrated>;
      sizes?: Array<SizeHydrated>;
    }

    export namespace _translations {
      export type FilterableFields = StringWithAutocomplete<
        | "name"
        | "slug"
        | "price"
        | "description"
        | "productImage"
        | "productImage[*].type"
        | "productImage[*].dataUrl"
        | "productGallery"
        | "productGallery[*].type"
        | "productGallery[*].dataUrl"
        | "sizes"
        | "sizes[*].type"
        | "sizes[*].dataUrl"
        | "__language"
      >;
    }

    // #endregion
  }

  // #endregion

  // #region size

  export interface SizeBase extends BaseObject<"size"> {
    size: string;
    icon?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>;
    description?: string;
    __translations?: Array<Size._translationsBase>;
  }

  export interface Size extends SizeBase {
    icon?: Array<DataLink>;
    __translations?: Array<Size._translations>;
  }

  export interface SizeHydrated extends SizeBase {
    icon?: Array<InternalMedia>;
    __translations?: Array<Size._translationsHydrated>;
  }

  export interface SizeHydratedTwice extends SizeBase {
    icon?: Array<InternalMediaHydrated>;
    __translations?: Array<Size._translationsHydratedTwice>;
  }

  export namespace Size {
    export type FilterableFields = StringWithAutocomplete<
      | "size"
      | "icon"
      | "icon[*].type"
      | "icon[*].dataUrl"
      | "description"
      | "__translations"
      | "__translations[*].size"
      | "__translations[*].icon"
      | "__translations[*].icon[*].type"
      | "__translations[*].icon[*].dataUrl"
      | "__translations[*].description"
      | "__translations[*].__language"
    >;

    // #region Size.__translations

    export interface _translationsBase {
      size: string;
      icon?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>;
      description?: string;
      __language: string;
    }

    export interface _translations extends _translationsBase {
      icon?: Array<DataLink>;
    }

    export interface _translationsHydrated extends _translationsBase {
      icon?: Array<InternalMedia>;
    }

    export interface _translationsHydratedTwice extends _translationsBase {
      icon?: Array<InternalMediaHydrated>;
    }

    export namespace _translations {
      export type FilterableFields = StringWithAutocomplete<
        | "size"
        | "icon"
        | "icon[*].type"
        | "icon[*].dataUrl"
        | "description"
        | "__language"
      >;
    }

    // #endregion
  }

  // #endregion

  export interface FlotiqObjectAPI {
    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;

    contact_form: ApiRequest<
      ContactForm,
      ContactFormHydrated,
      ContactFormHydratedTwice,
      ContactForm.FilterableFields
    >;

    product: ApiRequest<
      Product,
      ProductHydrated,
      ProductHydratedTwice,
      Product.FilterableFields
    >;

    size: ApiRequest<
      Size,
      SizeHydrated,
      SizeHydratedTwice,
      Size.FilterableFields
    >;
  }
}
