import type { Metadata } from 'next';
import { draftMode } from 'next/headers';
import './globals.css';
import { ReactNode } from 'react';
import Navbar from './_components/Navbar/Navbar';
import Footer from './_components/Footer/Footer';
import { DraftModeInfo } from './_components/DraftModeInfo/DraftModeInfo';
import NextTopLoader from 'nextjs-toploader';


export const metadata: Metadata = {
  title: 'Demo shop',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const { isEnabled } = await draftMode();
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <main>
          <Navbar />
          <NextTopLoader
              color="#0083FC"
              height={4}
              shadow=""
              template='<div class="bar shadow-[0_3px_5px_#015bd7a1,_0_0_0px_#015bd78f]" role="bar">'
              zIndex={100}
          />
          {isEnabled ? (
              <DraftModeInfo editorKey={process.env.FLOTIQ_EDITOR_KEY || ''} />
          ) : null}

          <div className="min-h-[70vh] pt-10 lg:pt-18">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
