import type { Metadata } from 'next';
import { draftMode } from 'next/headers';
import '../globals.css';
import { ReactNode } from 'react';
import Navbar from '../_components/Navbar/Navbar';
import Footer from '../_components/Footer/Footer';
import { DraftModeInfo } from '../_components/DraftModeInfo/DraftModeInfo';
import NextTopLoader from 'nextjs-toploader';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Demo shop',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'pl' }]
}

export default async function RootLayout(
  {
    children,
    params
  }: Readonly<{
    children: ReactNode
    params: Promise<{ lang: 'en' | 'pl' }>
  }>
) {
  const { isEnabled } = await draftMode();
  const { lang } = await params;
  return (
    <html lang={lang} className="scroll-smooth">
    <body>
    <main>
      <Navbar lang={lang}/>
      <NextTopLoader
        color="#0083FC"
        height={4}
        shadow=""
        template='<div class="bar shadow-[0_3px_5px_#015bd7a1,_0_0_0px_#015bd78f]" role="bar">'
        zIndex={100}
      />
      {isEnabled ? (
        <DraftModeInfo editorKey={process.env.FLOTIQ_EDITOR_KEY || ''}/>
      ) : null}

      <div className="min-h-[70vh] py-10 lg:py-18">{children}</div>
      <Footer lang={lang}/>
    </main>
    <Script
      src="https://fs3yzb3nh3.execute-api.us-east-1.amazonaws.com/prod-aws/flotiq-forms/contact_form-jq1__lENU"
      async
    />
    </body>
    </html>
  );
}
